### ISSUE TITLE
Option to use npmcdn file listing API instead of `npm install` to calculate metrics

### ISSUE THREAD

**Issue by bengummer** [nolanlawson/slow-deps#11]
It would be nice to have the option to run `slow-deps` in "fast mode", for cases where calculation time is more important than accuracy (such as when running slow-deps across many repos for comparison purposes).

If an option/flag such as `slow-deps --fast` was provided, the tool could skip the `npm install` process and instead:
1. recursively call https://npmcdn.com/slow-deps@1.1.3/?json (replacing the package name/version each time) to calculate the exact package size of each dependency.
2. calculate the estimated install timefor a package by assuming a fixed network speed (e.g. `install time = package size ÷ network speed`)

I'm happy to work on a PR for this at some stage if this kind of feature is of interest.

**Comment by nolanlawson** [comment]
Hi, this is not a feature I think I'm very interested in supporting (I like to measure actual npm install time), but I encourage you to fork and write a similar tool to do this. :) Maybe call it `fast-deps`? :wink:

**Comment by bengummer** [comment]
Ok no probs, thanks!
