### ISSUE TITLE
Implement a cache for performance

### ISSUE THREAD

**Issue by crazy4groovy** [nolanlawson/slow-deps#13]
I generally worry about tools like this slowing down npm even more. It would be nice to have a (local) cache of module dl speed/size results, at least per specific version. Perhaps even a centralized/hosted cache of speeds/sizes.

**Comment by nolanlawson** [comment]
This tool creates a local cache for each install, and does not interfere with the global npm cache. Regular `npm install`s will run the same before, during, and after you run `slow-deps`.
