### ISSUE TITLE
Add verbose messages informing which dependencies were skipped

### ISSUE THREAD

**Issue by sahildua2305** [nolanlawson/slow-deps#15]
Since we have flags `--production` and `--no-optional` we should show which dependencies are we skipping while analyzing the dependencies.

Something like this:

For `--production`:

```
Analyzing 15 dependencies (skipping devDependencies) ...
```

For `--no-optional`:

```
Analyzing 15 dependencies (skipping optionalDependencies) ...
```

For `--no-optional --production`:

```
Analyzing 15 dependencies (skipping devDependencies and optionalDependencies) ...
```

I have a fix ready for this. I'll push once #14 is merged.

/cc @nolanlawson

**Comment by nolanlawson** [comment]
Great idea! I think it would be nice to also include the numbers in there (`skipping 2 devDependencies`/`skipping 1 optionalDependency`).

**Comment by sahildua2305** [comment]
Yeah! That's a good idea. I'll push it later.

**Comment by nolanlawson** [comment]
Fixed, thank you very much!
