### ISSUE TITLE
Freaks out on projects with "file:/path/to/dep" dependency.

### ISSUE THREAD

**Issue by fahrradflucht** [nolanlawson/slow-deps#2]
I had [this project](https://github.com/bigardone/phoenix-trello) cloned down on my machine and ran slow-deps against it (just 4 fun).

It totally freaked out with an error log to big to include here. Running npm install on that project works just fine. I looked it up and according to [the docs](https://docs.npmjs.com/files/package.json#dependencies) this is a valid package.json.

**Comment by nolanlawson** [comment]
It should work now in 1.0.6 assuming you have an absolute path in there. Please reopen if not.

**Comment by ds82** [comment]
Is there a reason that it only works with absolute paths?
