### ISSUE TITLE
Feature request: Integrate network-emulation-conditions

### ISSUE THREAD

**Issue by siddharthkp** [nolanlawson/slow-deps#20]
Please add @addyosmani's [network-emulation-conditions](https://github.com/addyosmani/network-emulation-conditions) to simulate 3G, 4G speeds

**Comment by nolanlawson** [comment]
I'm not sure what feature you would like? That repo seems to only contain metadata; it does not configure the system to make speeds drop down within Node.js to simulate 3G, 4G, etc.

**Comment by siddharthkp** [comment]
@nolanlawson, oops! Sorry I misunderstood. 
My bad.
