### ISSUE TITLE
devDependencies should be optional

### ISSUE THREAD

**Issue by dtex** [nolanlawson/slow-deps#3]
They are not required for the majority of installs.

If you agree, I'll submit a PR with `dev` as a command line param to include them and have them not be included by default.

i.e. `slow-deps --dev`

**Comment by nolanlawson** [comment]
I prefer --production because it matches what npm does. And yes, I would accept the PR if you also update the README. :)

**Comment by dtex** [comment]
Rodger dodger, I'm on it

**Comment by nolanlawson** [comment]
fixed in #4, thanks!

**Comment by dtex** [comment]
Happy to do it. Thank _you_ for building slow-deps. 

I frequently worried about this but was too busy to dig.
