### ISSUE TITLE
Ignore optional dependencies

### ISSUE THREAD

**Issue by IanVS** [nolanlawson/slow-deps#5]
Could it be possible to avoid erroring out for `optionalDependencies`?  Maybe wrap that part in a try/catch?

**Comment by nolanlawson** [comment]
Hmm I'd be open to adding a `--no-optional` flag which is similar to how you avoid optional dependencies with `npm`. Open a PR? 😁

**Comment by sahildua2305** [comment]
I'd like to work on this in case @IanVS doesn't want to. :smile:

**Comment by IanVS** [comment]
Go for it. :)

**Comment by nolanlawson** [comment]
Hi @sahildua2305 have you started on this? If not I was going to. I was thinking of using `yargs` to parse the arguments.

**Comment by sahildua2305** [comment]
@nolanlawson Would you recommend me changing the entire structure to use `yargs` or just include another argument just like `--production` ? I'll get this fixed soon.

**Comment by nolanlawson** [comment]
I like `yargs` and would be :+1: for adding it. The `-h`/`--help` feature is especially nice.

**Comment by sahildua2305** [comment]
@nolanlawson I have added `yargs` in #16. 😄
