### ISSUE TITLE
Mark dev dependencies

### ISSUE THREAD

**Issue by Turbo87** [nolanlawson/slow-deps#6]
right now it is somewhat hard to figure out which dependency is a dev vs. production dependency without looking at the `package.json` file all the time. it would be awesome if the tool showed something like a `(dev)` suffix for the dev dependencies.

**Comment by nolanlawson** [comment]
How about a `--verbose` mode that shows the version and whether it's a devDep/optionalDep or not? Could just add two more columns.

**Comment by Turbo87** [comment]
I guess that would resolve the issue too. Good idea!

**Comment by nolanlawson** [comment]
I'll add this later tonight unless someone else wants to do it. Basically I'd like for either `-v` or `--verbose` to add two extra columns: `Type` (one of `dev`, `normal`, `optional`) and `Version` (just shows the installed version, handy for checking if a new version is smaller/faster).

**Comment by sahildua2305** [comment]
@nolanlawson I'd like to take this up over the weekend, in case this isn't urgent. Let me know :smile:

**Comment by nolanlawson** [comment]
@sahildua2305 Absolutely, go right ahead please. :)

**Comment by caueops** [comment]
👍  --verbose.

@sahildua2305 If you need help, let me know. :)

**Comment by sahildua2305** [comment]
Thanks for offering help @cauealves. I'm almost there. Will push the code once #14 is taken care of because it's bound to have conflicts.

**Comment by caueops** [comment]
Nice :)

**Comment by fvdm** [comment]
Great idea! Could you also please add total install time for dev and production individually?

That'd be really nice to include in CI tests.

**Comment by nolanlawson** [comment]
I'd like to consider this fixed; I think `--verbose` is a bit excessive, but I like @sahildua2305's `--no-optional` and `--production` fixes!
