### ISSUE TITLE
Should respect local .npmrc

### ISSUE THREAD

**Issue by jongamble** [nolanlawson/slow-deps#7]
While trying to run this on a private branch with unpublished repos, it errors out before displaying any of the data. Would be nice to try/catch those errors so we can still use it for our public dependencies.

**Comment by nolanlawson** [comment]
Whoops yeah, that's a bug. Should definitely skip unpublished.

**Comment by nolanlawson** [comment]
Wait, except wouldn't `npm install` on that project fail anyway due to the unpublished repos?

**Comment by jongamble** [comment]
<img width="912" alt="screen shot 2016-08-18 at 2 47 18 pm" src="https://cloud.githubusercontent.com/assets/1728864/17786433/c6362840-6552-11e6-8fc2-06e2cca54638.png">

I've been working on this project for about 10 months, so I assure you `npm install` is working 😉

**Comment by nolanlawson** [comment]
Ah so npm just skips unpublished packages? I did not know it did that.

OTOH shouldn't you remove those packages from your package.json?

**Comment by jongamble** [comment]
in our `.npmrc` file, it has the links to our gem fury registry (a private registry) where the packages are "privately published"

**Comment by marcbachmann** [comment]
I also just ran into this problem. I just wanted to create an issue that `npm install` in your script doesn't respect the local `.npmrc` file because it uses a different `cwd`. 

modules are published but as private module on npm. so they are namespaced.

**Comment by nolanlawson** [comment]
Mmmm yes it should copy the `.npmrc` file over. Thanks, I will fix this.

**Comment by nolanlawson** [comment]
Fixed in 1.1.2. 🐶
