### ISSUE TITLE
Skip private modules?

### ISSUE THREAD

**Issue by hnqlv** [nolanlawson/slow-deps#9]
@nolanlawson wondering if we should skip private modules. Thoughts?

**Comment by nolanlawson** [comment]
How do you npm install them if they're private? I kind of hoped this tool would work seamlessly with existing `package.json`s as-written. What kind of `package.json` do you have and how is it breaking?

**Comment by hnqlv** [comment]
@nolanlawson you have to `npm login` first otherwise the installation will fail. Not a big deal really but in my case I don't have access to the repository where private modules are. So I'd like to just ignore/remove them from the table.

**Comment by nolanlawson** [comment]
Hm I think in this case the best bet is to remove them from package.json and run again. Otherwise I'm not quite sure how to solve the problem within this tool...

**Comment by hnqlv** [comment]
Not really ideal since you could forget and commit the package.json I have one idea but need test its hypothesis. I'll close this issue for now and comment if I find a work around.
